Create ProfilePage
Nawigacja-SGGW/webapp pull request #39
Opened 2024-11-17 18:49 UTC by michalina-sz

2024-11-17 18:52 UTC, michalmlk requested changes

2024-11-17 18:52 UTC, michalmlk commented on src/App.tsx
> +          element: <ProfilePage profileImage={undefined} />,
we should consider fetching data directly in profile page in future instead of passing them in props

2024-11-17 18:52 UTC, michalmlk commented on src/pages/ProfilePage/ProfilePage.scss
> +  padding: 20px 30px;
please define and use css variables

2024-11-17 18:52 UTC, michalmlk commented on src/pages/ProfilePage/ProfilePage.tsx
> +        {/* {profileImage ? (
?

2024-12-15 19:12 UTC, MariuszAKS approved these changes

2024-12-15 19:13 UTC, michalmlk approved these changes

2024-12-15 19:13 UTC, merged